### ISSUE TITLE
150304

### ISSUE THREAD

**Issue by wadewilliams** [jacksonhole/meetup#7]
## Intro
- Ok. Hi everyone, my name's Wade Williams
  <slide>
- A little background on me
  - From Lynn, Massachusetts
  - First computer was an Mac SE. When did you get your first computer? 21 or older? 18? 15? 12? 9? I learned to spell using a mac [seriously who would use this software](https://www.youtube.com/watch?v=dBmeU-OI15g&t=0m31s)
- Company [I work for Local Motors](https://localmotors.com/wadewilliams)
- We're based out of Phoenix. We work together with a global community of designers, engineers, fabricators and enthusiasts to innovate new Vehicles, starting with [This](https://rallyfighter.com) we're also selling [Drift Trikes](https://localmotors.com/drift-trike) and we recently co-created [The world's first 3d Printed Car](https://localmotors.com/3dprintedcar)
## Implementing vs Building
- Lean Startup: ["Instead of building a website and a large database of footwear, [Zappos] approached local shoe stores, took pictures of their inventory, posted the pictures online, bought the shoes from the stores at full price, and sold them directly to customers if they purchased the shoe through his website."](http://en.wikipedia.org/wiki/Lean_startup#Minimum_viable_product)
- Good Reasons
  - Solves a problem for the first time (unlikely)
  - Solves a problem 10x better than the closest competition
  - You're learning. Importance not to be underestimated 
## Why are you Building Software
- fun & profit ? 
- to acheive some goal ? 
- Maybe we should make better choices about how we can achieve success metrics while also implementing the absolute minimum amount of software
- [Impact Mapping](http://impactmapping.org) by [Gojko Adzic](https://www.google.com/webhp?hl=en#q=gojko+adzic&hl=en&tbm=vid)
## Software worth Using
- GitHub
  - https://github.com/wadewilliams/webhook-receiver
  - @ctro @novaugust turn on 2FA
- Slack
  - API
  - https://slack.com/integrations
- Segment.io
  - API
  - https://segment.com/integrations
## Software that's really interesting that could be worth using but you probably should think hard if you really need it. Deploy with extreme prejudice
- Inspectlet
- Intercom.io
- Compose.io
- RedisLabs
- Keen.io
- Runscope && GhostInspector
- Sentry
- Choir.io
## Jackson Hole Tech Scene
- github.com/jacksonhole
- coderdojo.com
- codestarter.org

**Comment by jprobst21** [comment]
Hi Wade!

**Comment by novaugust** [comment]
It's cute that you did this as an issue. I would've PR'd, personally :D

**Comment by wadewilliams** [comment]
@novaugust I'm not sure if it's good enough for a pull request yet. Just starting the conversation :8ball:

**Comment by wadewilliams** [comment]
@devmoxie
